# Generated by Django 2.1.1 on 2018-09-17 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChangeEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_ip', models.CharField(max_length=16)),
                ('client_ip', models.CharField(max_length=16)),
                ('client_id', models.CharField(max_length=128)),
                ('color', models.CharField(max_length=64)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
